# -*- coding: utf-8 -*-
"""beautifulsoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aOzqLrVTC_EWwXjvp7j4-A7IFrJxbtbQ
"""

import bs4
import requests

base_url = 'https://www.dictionary.com/browse/{}'

# Assuming 'search' is a predefined variable holding the word you're searching for
search = "friend"  # replace with your word
res1 = requests.get(base_url.format(search))

soup = bs4.BeautifulSoup(res1.text, features='html.parser')
example = soup.findAll('span', {'luna-example italic'})
example1 = str(example[0].text)
final_example = example1.strip().capitalize()
print(final_example)
print("hello")

from google.colab import drive
drive.mount('/content/drive')

